Add the French language
planetdecred/dcrios pull request #726
Opened 2020-11-03 09:36 UTC by JustinBeBoy

Add Localizable.strings file for the French language

2020-11-03 10:38 UTC, macsleven requested changes

2020-11-03 10:38 UTC, macsleven commented on Decred Wallet/fr.lproj/Localizable.strings
> +// Copyright (c) 2018-2020 The Decred developers
```suggestion
// Copyright (c) 2020 The Decred developers
```

2020-11-03 10:38 UTC, macsleven commented on Decred Wallet/fr.lproj/Localizable.strings
> +"lockedByTickets" = "label_locked_by_tickets";
is this correct?

2020-11-14 08:04 UTC, JustinBeBoy commented on Decred Wallet/fr.lproj/Localizable.strings
> +"lockedByTickets" = "label_locked_by_tickets";
It has been resolved.

2020-11-26 11:23 UTC, macsleven approved these changes

2020-11-26 11:23 UTC, merged