implement account filter operation on privacy setup
planetdecred/dcrios pull request #765
Opened 2021-05-20 00:44 UTC by macsleven

This PR implements the appropriate account to display on the send view for both privacy wallet and non privacy wallet.

- Implements support for iOS 11

<img height="500" alt="Screenshot 2021-05-20 at 01 42 09" src="https://user-images.githubusercontent.com/794430/118902053-bad1f480-b90c-11eb-8d24-2530b8f78c0b.png">
<img height="500" alt="Screenshot 2021-05-20 at 01 42 30" src="https://user-images.githubusercontent.com/794430/118902057-bc032180-b90c-11eb-8d16-6fb081feb9d4.png">
<img height="500" alt="Screenshot 2021-05-20 at 01 42 44" src="https://user-images.githubusercontent.com/794430/118902062-be657b80-b90c-11eb-9db7-781ce89dd4e4.png">

2021-05-20 14:59 UTC, dreacot commented
while sending to self, I can still see my mixed account in the receiving account dialog.

I think this happens if your balance in the mixed account is greater than zero

<img src="https://user-images.githubusercontent.com/25265396/119001644-0ffd1d00-b984-11eb-94d1-aed666d6d546.png" width="300" />

2021-05-23 21:47 UTC, dreacot submitted a review, later dismissed

2021-05-24 13:13 UTC, C-ollins requested changes
- When I tap `send to self`, it changes the From account `mixed` to `default`, this is probably happening because `default` is the first account on my list but it should not change because `mixed` is valid for sending to self.
- When sending to self, I'm allowed to send from an unmixed account to my second wallet's account. The second wallet is technically "send to others" so tapping an account from another wallet should set the `From` account to allow only mixed.

2021-05-24 13:33 UTC, C-ollins commented
Accounts from my second wallet are not visible when sending to address and the wallet does not have privacy enabled.

<img src="https://user-images.githubusercontent.com/19960200/119355148-d5a1c180-bc9c-11eb-91d4-74f7a1e10bd8.jpeg" width="300">

2021-05-28 14:24 UTC, dreacot approved these changes

2021-05-28 14:28 UTC, C-ollins approved these changes

2021-05-28 14:28 UTC, merged