update codebase to dcrlibwallet master
planetdecred/dcrios pull request #815
Opened 2021-08-13 22:51 UTC by macsleven

- Update codebase 
- Upgrade Dcrlibwallet

2021-08-14 06:30 UTC, dreacot requested changes

2021-08-14 06:30 UTC, dreacot commented on Decred Wallet/BuildConfig.swift
> +    static let PoliteiaHost = DcrlibwalletPoliteiaMainnetHost
```suggestion
    static let PoliteiaHost = DcrlibwalletPoliteiaTestnetHost
```

2021-08-14 06:30 UTC, dreacot commented on Decred Wallet/BuildConfig.swift
> +    static let PoliteiaHost = DcrlibwalletPoliteiaTestnetHost
```suggestion
    static let PoliteiaHost = DcrlibwalletPoliteiaMainnetHost
```

2021-08-14 06:34 UTC, dreacot commented on Decred Wallet/Features/TransactionDetails/TransactionDetailsViewController.swift
> +       // let txHash = Data(fromHexEncodedString: self.transactionHash!)!
remove comment

2021-08-16 01:38 UTC, JustinBeBoy approved these changes

2021-08-16 13:37 UTC, dreacot approved these changes

2021-08-16 13:38 UTC, merged