biometrics using Touch ID/ Face ID for spending password/PIN
planetdecred/dcrios pull request #883
Opened 2021-12-27 10:31 UTC by JustinBeBoy

Resolve #632 
This PR updated:
- Allow user using biometrics is option for spending password/PIN
- Add setting biometrics for spending password/PIN
- Refactor code

**Screenshot**
|<img src="https://user-images.githubusercontent.com/19331824/147463066-c941aace-5644-4621-bf29-4f62062bba4e.PNG" height="500" style="max-width: 100%;">|<img src="https://user-images.githubusercontent.com/19331824/147463070-d83fb93d-ff44-430b-b00a-6b24ed9494a2.PNG" height="500" style="max-width: 100%;">|
|-|-|

2022-01-04 23:55 UTC, macsleven requested changes
App crashed when launched on customTabMenuView.
line 57: (self.subviews[previousTabId] as! TabMenuItemView).deactivate()

2022-01-31 23:25 UTC, macsleven submitted a review, later dismissed
Biometrics needs to be implemented here
<img height="500" alt="Screenshot 2021-09-27 at 21 59 44" src="https://user-images.githubusercontent.com/794430/151889266-39806495-0d23-4536-9104-772e8bb7efe4.PNG">

<img height="500" alt="Screenshot 2021-09-27 at 21 59 44" src="https://user-images.githubusercontent.com/794430/151889287-d815fd2c-1372-4f31-adb6-59a20fb8a5ec.PNG">

<img height="500" alt="Screenshot 2021-09-27 at 21 59 44" src="https://user-images.githubusercontent.com/794430/151889294-ac843af4-ecce-4b0f-bdc9-838aca5be33d.PNG">

<img height="500" alt="Screenshot 2021-09-27 at 21 59 44" src="https://user-images.githubusercontent.com/794430/151889304-1b90b52b-9be2-4d83-9832-1950968b5896.PNG">

2022-02-04 20:37 UTC, Clariceco commented
For consistency purposes, can you please capitalize "password". I have circled it in red. Thank you! <img width="399" alt="Screen Shot 2022-02-04 at 12 19 38 PM" src="https://user-images.githubusercontent.com/88850617/152597935-80a89f9a-84de-451a-a761-5a4c18c51c1a.png">

2022-04-08 16:56 UTC, dreacot approved these changes

2022-04-08 17:01 UTC, merged